export const SET_FORM_DATA = 'SET_FORM_DATA';
export const CLEAR_PASSWORD_ERROR = 'CLEAR_PASSWORD_ERROR';
export const CLEAR_FORM_DATA = 'CLEAR_FORM_DATA';
export const PASSWORD_DATA = 'mod7ReactUSIP';